// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role.proto

package com.mokylin.game.server.proto.bean;

public final class RoleProto {
  private RoleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RoleDataProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RoleDataProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 sex = 3;</code>
     */
    boolean hasSex();
    /**
     * <code>required int32 sex = 3;</code>
     */
    int getSex();

    /**
     * <code>required .MapDataProto map = 4;</code>
     */
    boolean hasMap();
    /**
     * <code>required .MapDataProto map = 4;</code>
     */
    com.mokylin.game.server.proto.bean.MapProto.MapDataProto getMap();
    /**
     * <code>required .MapDataProto map = 4;</code>
     */
    com.mokylin.game.server.proto.bean.MapProto.MapDataProtoOrBuilder getMapOrBuilder();
  }
  /**
   * Protobuf type {@code RoleDataProto}
   */
  public static final class RoleDataProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RoleDataProto)
      RoleDataProtoOrBuilder {
    // Use RoleDataProto.newBuilder() to construct.
    private RoleDataProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RoleDataProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RoleDataProto defaultInstance;
    public static RoleDataProto getDefaultInstance() {
      return defaultInstance;
    }

    public RoleDataProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RoleDataProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sex_ = input.readInt32();
              break;
            }
            case 34: {
              com.mokylin.game.server.proto.bean.MapProto.MapDataProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = map_.toBuilder();
              }
              map_ = input.readMessage(com.mokylin.game.server.proto.bean.MapProto.MapDataProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(map_);
                map_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mokylin.game.server.proto.bean.RoleProto.internal_static_RoleDataProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mokylin.game.server.proto.bean.RoleProto.internal_static_RoleDataProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto.class, com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto.Builder.class);
    }

    public static com.google.protobuf.Parser<RoleDataProto> PARSER =
        new com.google.protobuf.AbstractParser<RoleDataProto>() {
      public RoleDataProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoleDataProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RoleDataProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private int sex_;
    /**
     * <code>required int32 sex = 3;</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 sex = 3;</code>
     */
    public int getSex() {
      return sex_;
    }

    public static final int MAP_FIELD_NUMBER = 4;
    private com.mokylin.game.server.proto.bean.MapProto.MapDataProto map_;
    /**
     * <code>required .MapDataProto map = 4;</code>
     */
    public boolean hasMap() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .MapDataProto map = 4;</code>
     */
    public com.mokylin.game.server.proto.bean.MapProto.MapDataProto getMap() {
      return map_;
    }
    /**
     * <code>required .MapDataProto map = 4;</code>
     */
    public com.mokylin.game.server.proto.bean.MapProto.MapDataProtoOrBuilder getMapOrBuilder() {
      return map_;
    }

    private void initFields() {
      id_ = 0L;
      name_ = "";
      sex_ = 0;
      map_ = com.mokylin.game.server.proto.bean.MapProto.MapDataProto.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMap()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMap().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, sex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, map_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, map_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RoleDataProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RoleDataProto)
        com.mokylin.game.server.proto.bean.RoleProto.RoleDataProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mokylin.game.server.proto.bean.RoleProto.internal_static_RoleDataProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mokylin.game.server.proto.bean.RoleProto.internal_static_RoleDataProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto.class, com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto.Builder.class);
      }

      // Construct using com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMapFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        sex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (mapBuilder_ == null) {
          map_ = com.mokylin.game.server.proto.bean.MapProto.MapDataProto.getDefaultInstance();
        } else {
          mapBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mokylin.game.server.proto.bean.RoleProto.internal_static_RoleDataProto_descriptor;
      }

      public com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto getDefaultInstanceForType() {
        return com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto.getDefaultInstance();
      }

      public com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto build() {
        com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto buildPartial() {
        com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto result = new com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (mapBuilder_ == null) {
          result.map_ = map_;
        } else {
          result.map_ = mapBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto) {
          return mergeFrom((com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto other) {
        if (other == com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasMap()) {
          mergeMap(other.getMap());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasSex()) {
          
          return false;
        }
        if (!hasMap()) {
          
          return false;
        }
        if (!getMap().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mokylin.game.server.proto.bean.RoleProto.RoleDataProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private int sex_ ;
      /**
       * <code>required int32 sex = 3;</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 sex = 3;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <code>required int32 sex = 3;</code>
       */
      public Builder setSex(int value) {
        bitField0_ |= 0x00000004;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sex = 3;</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sex_ = 0;
        onChanged();
        return this;
      }

      private com.mokylin.game.server.proto.bean.MapProto.MapDataProto map_ = com.mokylin.game.server.proto.bean.MapProto.MapDataProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.mokylin.game.server.proto.bean.MapProto.MapDataProto, com.mokylin.game.server.proto.bean.MapProto.MapDataProto.Builder, com.mokylin.game.server.proto.bean.MapProto.MapDataProtoOrBuilder> mapBuilder_;
      /**
       * <code>required .MapDataProto map = 4;</code>
       */
      public boolean hasMap() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .MapDataProto map = 4;</code>
       */
      public com.mokylin.game.server.proto.bean.MapProto.MapDataProto getMap() {
        if (mapBuilder_ == null) {
          return map_;
        } else {
          return mapBuilder_.getMessage();
        }
      }
      /**
       * <code>required .MapDataProto map = 4;</code>
       */
      public Builder setMap(com.mokylin.game.server.proto.bean.MapProto.MapDataProto value) {
        if (mapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          map_ = value;
          onChanged();
        } else {
          mapBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .MapDataProto map = 4;</code>
       */
      public Builder setMap(
          com.mokylin.game.server.proto.bean.MapProto.MapDataProto.Builder builderForValue) {
        if (mapBuilder_ == null) {
          map_ = builderForValue.build();
          onChanged();
        } else {
          mapBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .MapDataProto map = 4;</code>
       */
      public Builder mergeMap(com.mokylin.game.server.proto.bean.MapProto.MapDataProto value) {
        if (mapBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              map_ != com.mokylin.game.server.proto.bean.MapProto.MapDataProto.getDefaultInstance()) {
            map_ =
              com.mokylin.game.server.proto.bean.MapProto.MapDataProto.newBuilder(map_).mergeFrom(value).buildPartial();
          } else {
            map_ = value;
          }
          onChanged();
        } else {
          mapBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .MapDataProto map = 4;</code>
       */
      public Builder clearMap() {
        if (mapBuilder_ == null) {
          map_ = com.mokylin.game.server.proto.bean.MapProto.MapDataProto.getDefaultInstance();
          onChanged();
        } else {
          mapBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>required .MapDataProto map = 4;</code>
       */
      public com.mokylin.game.server.proto.bean.MapProto.MapDataProto.Builder getMapBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getMapFieldBuilder().getBuilder();
      }
      /**
       * <code>required .MapDataProto map = 4;</code>
       */
      public com.mokylin.game.server.proto.bean.MapProto.MapDataProtoOrBuilder getMapOrBuilder() {
        if (mapBuilder_ != null) {
          return mapBuilder_.getMessageOrBuilder();
        } else {
          return map_;
        }
      }
      /**
       * <code>required .MapDataProto map = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.mokylin.game.server.proto.bean.MapProto.MapDataProto, com.mokylin.game.server.proto.bean.MapProto.MapDataProto.Builder, com.mokylin.game.server.proto.bean.MapProto.MapDataProtoOrBuilder> 
          getMapFieldBuilder() {
        if (mapBuilder_ == null) {
          mapBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.mokylin.game.server.proto.bean.MapProto.MapDataProto, com.mokylin.game.server.proto.bean.MapProto.MapDataProto.Builder, com.mokylin.game.server.proto.bean.MapProto.MapDataProtoOrBuilder>(
                  getMap(),
                  getParentForChildren(),
                  isClean());
          map_ = null;
        }
        return mapBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:RoleDataProto)
    }

    static {
      defaultInstance = new RoleDataProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RoleDataProto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoleDataProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RoleDataProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nrole.proto\032\tmap.proto\"R\n\rRoleDataProto" +
      "\022\n\n\002id\030\001 \002(\003\022\014\n\004name\030\002 \002(\t\022\013\n\003sex\030\003 \002(\005\022" +
      "\032\n\003map\030\004 \002(\0132\r.MapDataProtoB/\n\"com.mokyl" +
      "in.game.server.proto.beanB\tRoleProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.mokylin.game.server.proto.bean.MapProto.getDescriptor(),
        }, assigner);
    internal_static_RoleDataProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RoleDataProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RoleDataProto_descriptor,
        new java.lang.String[] { "Id", "Name", "Sex", "Map", });
    com.mokylin.game.server.proto.bean.MapProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
