// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role.proto

package com.mokylin.game.server.logic.role.proto;

public final class RoleProto {
  private RoleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MapDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MapData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 model = 1;</code>
     */
    boolean hasModel();
    /**
     * <code>required int32 model = 1;</code>
     */
    int getModel();

    /**
     * <code>required int32 x = 2;</code>
     */
    boolean hasX();
    /**
     * <code>required int32 x = 2;</code>
     */
    int getX();

    /**
     * <code>required int32 y = 3;</code>
     */
    boolean hasY();
    /**
     * <code>required int32 y = 3;</code>
     */
    int getY();
  }
  /**
   * Protobuf type {@code MapData}
   */
  public static final class MapData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MapData)
      MapDataOrBuilder {
    // Use MapData.newBuilder() to construct.
    private MapData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MapData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MapData defaultInstance;
    public static MapData getDefaultInstance() {
      return defaultInstance;
    }

    public MapData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MapData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              model_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              x_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              y_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mokylin.game.server.logic.role.proto.RoleProto.internal_static_MapData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mokylin.game.server.logic.role.proto.RoleProto.internal_static_MapData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mokylin.game.server.logic.role.proto.RoleProto.MapData.class, com.mokylin.game.server.logic.role.proto.RoleProto.MapData.Builder.class);
    }

    public static com.google.protobuf.Parser<MapData> PARSER =
        new com.google.protobuf.AbstractParser<MapData>() {
      public MapData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MapData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MapData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MODEL_FIELD_NUMBER = 1;
    private int model_;
    /**
     * <code>required int32 model = 1;</code>
     */
    public boolean hasModel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 model = 1;</code>
     */
    public int getModel() {
      return model_;
    }

    public static final int X_FIELD_NUMBER = 2;
    private int x_;
    /**
     * <code>required int32 x = 2;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 x = 2;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 3;
    private int y_;
    /**
     * <code>required int32 y = 3;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 y = 3;</code>
     */
    public int getY() {
      return y_;
    }

    private void initFields() {
      model_ = 0;
      x_ = 0;
      y_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasModel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, model_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, y_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, model_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mokylin.game.server.logic.role.proto.RoleProto.MapData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.MapData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.MapData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.MapData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.MapData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.MapData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.MapData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.MapData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.MapData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.MapData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mokylin.game.server.logic.role.proto.RoleProto.MapData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MapData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MapData)
        com.mokylin.game.server.logic.role.proto.RoleProto.MapDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mokylin.game.server.logic.role.proto.RoleProto.internal_static_MapData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mokylin.game.server.logic.role.proto.RoleProto.internal_static_MapData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mokylin.game.server.logic.role.proto.RoleProto.MapData.class, com.mokylin.game.server.logic.role.proto.RoleProto.MapData.Builder.class);
      }

      // Construct using com.mokylin.game.server.logic.role.proto.RoleProto.MapData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        model_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mokylin.game.server.logic.role.proto.RoleProto.internal_static_MapData_descriptor;
      }

      public com.mokylin.game.server.logic.role.proto.RoleProto.MapData getDefaultInstanceForType() {
        return com.mokylin.game.server.logic.role.proto.RoleProto.MapData.getDefaultInstance();
      }

      public com.mokylin.game.server.logic.role.proto.RoleProto.MapData build() {
        com.mokylin.game.server.logic.role.proto.RoleProto.MapData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mokylin.game.server.logic.role.proto.RoleProto.MapData buildPartial() {
        com.mokylin.game.server.logic.role.proto.RoleProto.MapData result = new com.mokylin.game.server.logic.role.proto.RoleProto.MapData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.model_ = model_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mokylin.game.server.logic.role.proto.RoleProto.MapData) {
          return mergeFrom((com.mokylin.game.server.logic.role.proto.RoleProto.MapData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mokylin.game.server.logic.role.proto.RoleProto.MapData other) {
        if (other == com.mokylin.game.server.logic.role.proto.RoleProto.MapData.getDefaultInstance()) return this;
        if (other.hasModel()) {
          setModel(other.getModel());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasModel()) {
          
          return false;
        }
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mokylin.game.server.logic.role.proto.RoleProto.MapData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mokylin.game.server.logic.role.proto.RoleProto.MapData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int model_ ;
      /**
       * <code>required int32 model = 1;</code>
       */
      public boolean hasModel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 model = 1;</code>
       */
      public int getModel() {
        return model_;
      }
      /**
       * <code>required int32 model = 1;</code>
       */
      public Builder setModel(int value) {
        bitField0_ |= 0x00000001;
        model_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 model = 1;</code>
       */
      public Builder clearModel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        model_ = 0;
        onChanged();
        return this;
      }

      private int x_ ;
      /**
       * <code>required int32 x = 2;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 x = 2;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>required int32 x = 2;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000002;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 x = 2;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>required int32 y = 3;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 y = 3;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>required int32 y = 3;</code>
       */
      public Builder setY(int value) {
        bitField0_ |= 0x00000004;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 y = 3;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MapData)
    }

    static {
      defaultInstance = new MapData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MapData)
  }

  public interface RoleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Role)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 sex = 3;</code>
     */
    boolean hasSex();
    /**
     * <code>required int32 sex = 3;</code>
     */
    int getSex();

    /**
     * <code>required .MapData mapData = 4;</code>
     */
    boolean hasMapData();
    /**
     * <code>required .MapData mapData = 4;</code>
     */
    com.mokylin.game.server.logic.role.proto.RoleProto.MapData getMapData();
    /**
     * <code>required .MapData mapData = 4;</code>
     */
    com.mokylin.game.server.logic.role.proto.RoleProto.MapDataOrBuilder getMapDataOrBuilder();
  }
  /**
   * Protobuf type {@code Role}
   */
  public static final class Role extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Role)
      RoleOrBuilder {
    // Use Role.newBuilder() to construct.
    private Role(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Role(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Role defaultInstance;
    public static Role getDefaultInstance() {
      return defaultInstance;
    }

    public Role getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Role(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sex_ = input.readInt32();
              break;
            }
            case 34: {
              com.mokylin.game.server.logic.role.proto.RoleProto.MapData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = mapData_.toBuilder();
              }
              mapData_ = input.readMessage(com.mokylin.game.server.logic.role.proto.RoleProto.MapData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(mapData_);
                mapData_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mokylin.game.server.logic.role.proto.RoleProto.internal_static_Role_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mokylin.game.server.logic.role.proto.RoleProto.internal_static_Role_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mokylin.game.server.logic.role.proto.RoleProto.Role.class, com.mokylin.game.server.logic.role.proto.RoleProto.Role.Builder.class);
    }

    public static com.google.protobuf.Parser<Role> PARSER =
        new com.google.protobuf.AbstractParser<Role>() {
      public Role parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Role(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Role> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private int sex_;
    /**
     * <code>required int32 sex = 3;</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 sex = 3;</code>
     */
    public int getSex() {
      return sex_;
    }

    public static final int MAPDATA_FIELD_NUMBER = 4;
    private com.mokylin.game.server.logic.role.proto.RoleProto.MapData mapData_;
    /**
     * <code>required .MapData mapData = 4;</code>
     */
    public boolean hasMapData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .MapData mapData = 4;</code>
     */
    public com.mokylin.game.server.logic.role.proto.RoleProto.MapData getMapData() {
      return mapData_;
    }
    /**
     * <code>required .MapData mapData = 4;</code>
     */
    public com.mokylin.game.server.logic.role.proto.RoleProto.MapDataOrBuilder getMapDataOrBuilder() {
      return mapData_;
    }

    private void initFields() {
      id_ = 0L;
      name_ = "";
      sex_ = 0;
      mapData_ = com.mokylin.game.server.logic.role.proto.RoleProto.MapData.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMapData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMapData().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, sex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, mapData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, mapData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mokylin.game.server.logic.role.proto.RoleProto.Role parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.Role parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.Role parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.Role parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.Role parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.Role parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.Role parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.Role parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.Role parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mokylin.game.server.logic.role.proto.RoleProto.Role parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mokylin.game.server.logic.role.proto.RoleProto.Role prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Role}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Role)
        com.mokylin.game.server.logic.role.proto.RoleProto.RoleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mokylin.game.server.logic.role.proto.RoleProto.internal_static_Role_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mokylin.game.server.logic.role.proto.RoleProto.internal_static_Role_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mokylin.game.server.logic.role.proto.RoleProto.Role.class, com.mokylin.game.server.logic.role.proto.RoleProto.Role.Builder.class);
      }

      // Construct using com.mokylin.game.server.logic.role.proto.RoleProto.Role.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMapDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        sex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (mapDataBuilder_ == null) {
          mapData_ = com.mokylin.game.server.logic.role.proto.RoleProto.MapData.getDefaultInstance();
        } else {
          mapDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mokylin.game.server.logic.role.proto.RoleProto.internal_static_Role_descriptor;
      }

      public com.mokylin.game.server.logic.role.proto.RoleProto.Role getDefaultInstanceForType() {
        return com.mokylin.game.server.logic.role.proto.RoleProto.Role.getDefaultInstance();
      }

      public com.mokylin.game.server.logic.role.proto.RoleProto.Role build() {
        com.mokylin.game.server.logic.role.proto.RoleProto.Role result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mokylin.game.server.logic.role.proto.RoleProto.Role buildPartial() {
        com.mokylin.game.server.logic.role.proto.RoleProto.Role result = new com.mokylin.game.server.logic.role.proto.RoleProto.Role(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (mapDataBuilder_ == null) {
          result.mapData_ = mapData_;
        } else {
          result.mapData_ = mapDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mokylin.game.server.logic.role.proto.RoleProto.Role) {
          return mergeFrom((com.mokylin.game.server.logic.role.proto.RoleProto.Role)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mokylin.game.server.logic.role.proto.RoleProto.Role other) {
        if (other == com.mokylin.game.server.logic.role.proto.RoleProto.Role.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasMapData()) {
          mergeMapData(other.getMapData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasSex()) {
          
          return false;
        }
        if (!hasMapData()) {
          
          return false;
        }
        if (!getMapData().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mokylin.game.server.logic.role.proto.RoleProto.Role parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mokylin.game.server.logic.role.proto.RoleProto.Role) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private int sex_ ;
      /**
       * <code>required int32 sex = 3;</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 sex = 3;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <code>required int32 sex = 3;</code>
       */
      public Builder setSex(int value) {
        bitField0_ |= 0x00000004;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sex = 3;</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sex_ = 0;
        onChanged();
        return this;
      }

      private com.mokylin.game.server.logic.role.proto.RoleProto.MapData mapData_ = com.mokylin.game.server.logic.role.proto.RoleProto.MapData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.mokylin.game.server.logic.role.proto.RoleProto.MapData, com.mokylin.game.server.logic.role.proto.RoleProto.MapData.Builder, com.mokylin.game.server.logic.role.proto.RoleProto.MapDataOrBuilder> mapDataBuilder_;
      /**
       * <code>required .MapData mapData = 4;</code>
       */
      public boolean hasMapData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .MapData mapData = 4;</code>
       */
      public com.mokylin.game.server.logic.role.proto.RoleProto.MapData getMapData() {
        if (mapDataBuilder_ == null) {
          return mapData_;
        } else {
          return mapDataBuilder_.getMessage();
        }
      }
      /**
       * <code>required .MapData mapData = 4;</code>
       */
      public Builder setMapData(com.mokylin.game.server.logic.role.proto.RoleProto.MapData value) {
        if (mapDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mapData_ = value;
          onChanged();
        } else {
          mapDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .MapData mapData = 4;</code>
       */
      public Builder setMapData(
          com.mokylin.game.server.logic.role.proto.RoleProto.MapData.Builder builderForValue) {
        if (mapDataBuilder_ == null) {
          mapData_ = builderForValue.build();
          onChanged();
        } else {
          mapDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .MapData mapData = 4;</code>
       */
      public Builder mergeMapData(com.mokylin.game.server.logic.role.proto.RoleProto.MapData value) {
        if (mapDataBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              mapData_ != com.mokylin.game.server.logic.role.proto.RoleProto.MapData.getDefaultInstance()) {
            mapData_ =
              com.mokylin.game.server.logic.role.proto.RoleProto.MapData.newBuilder(mapData_).mergeFrom(value).buildPartial();
          } else {
            mapData_ = value;
          }
          onChanged();
        } else {
          mapDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .MapData mapData = 4;</code>
       */
      public Builder clearMapData() {
        if (mapDataBuilder_ == null) {
          mapData_ = com.mokylin.game.server.logic.role.proto.RoleProto.MapData.getDefaultInstance();
          onChanged();
        } else {
          mapDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>required .MapData mapData = 4;</code>
       */
      public com.mokylin.game.server.logic.role.proto.RoleProto.MapData.Builder getMapDataBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getMapDataFieldBuilder().getBuilder();
      }
      /**
       * <code>required .MapData mapData = 4;</code>
       */
      public com.mokylin.game.server.logic.role.proto.RoleProto.MapDataOrBuilder getMapDataOrBuilder() {
        if (mapDataBuilder_ != null) {
          return mapDataBuilder_.getMessageOrBuilder();
        } else {
          return mapData_;
        }
      }
      /**
       * <code>required .MapData mapData = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.mokylin.game.server.logic.role.proto.RoleProto.MapData, com.mokylin.game.server.logic.role.proto.RoleProto.MapData.Builder, com.mokylin.game.server.logic.role.proto.RoleProto.MapDataOrBuilder> 
          getMapDataFieldBuilder() {
        if (mapDataBuilder_ == null) {
          mapDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.mokylin.game.server.logic.role.proto.RoleProto.MapData, com.mokylin.game.server.logic.role.proto.RoleProto.MapData.Builder, com.mokylin.game.server.logic.role.proto.RoleProto.MapDataOrBuilder>(
                  getMapData(),
                  getParentForChildren(),
                  isClean());
          mapData_ = null;
        }
        return mapDataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Role)
    }

    static {
      defaultInstance = new Role(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Role)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MapData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MapData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Role_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Role_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nrole.proto\".\n\007MapData\022\r\n\005model\030\001 \002(\005\022\t" +
      "\n\001x\030\002 \002(\005\022\t\n\001y\030\003 \002(\005\"H\n\004Role\022\n\n\002id\030\001 \002(\003" +
      "\022\014\n\004name\030\002 \002(\t\022\013\n\003sex\030\003 \002(\005\022\031\n\007mapData\030\004" +
      " \002(\0132\010.MapDataB5\n(com.mokylin.game.serve" +
      "r.logic.role.protoB\tRoleProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MapData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MapData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MapData_descriptor,
        new java.lang.String[] { "Model", "X", "Y", });
    internal_static_Role_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Role_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Role_descriptor,
        new java.lang.String[] { "Id", "Name", "Sex", "MapData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
