package com.mokylin.game.robot.message.manager;

import com.mokylin.game.core.message.MessagePool;

public class MessageManager {

	public boolean init() {
				MessagePool.getInstance().register(211203, com.mokylin.game.robot.logic.butterfly.handler.ResEndButterflyHandler.class, com.mokylin.game.robot.logic.butterfly.message.ResEndButterflyMessage.class);
		MessagePool.getInstance().register(211202, com.mokylin.game.robot.logic.butterfly.handler.ResStartButterflyHandler.class, com.mokylin.game.robot.logic.butterfly.message.ResStartButterflyMessage.class);
		MessagePool.getInstance().register(211201, com.mokylin.game.robot.logic.butterfly.handler.ResEnterButterflyHandler.class, com.mokylin.game.robot.logic.butterfly.message.ResEnterButterflyMessage.class);
		MessagePool.getInstance().register(100101, com.mokylin.game.robot.logic.login.handler.ResCreatePlayerHandler.class, com.mokylin.game.robot.logic.login.message.ResCreatePlayerMessage.class);
		MessagePool.getInstance().register(211207, com.mokylin.game.robot.logic.butterfly.handler.ResAddButterflyDefendHandler.class, com.mokylin.game.robot.logic.butterfly.message.ResAddButterflyDefendMessage.class);
		MessagePool.getInstance().register(211206, com.mokylin.game.robot.logic.butterfly.handler.ResButterflyFightNowHandler.class, com.mokylin.game.robot.logic.butterfly.message.ResButterflyFightNowMessage.class);
		MessagePool.getInstance().register(100103, com.mokylin.game.robot.logic.login.handler.ResCreatePlayerResultHandler.class, com.mokylin.game.robot.logic.login.message.ResCreatePlayerResultMessage.class);
		MessagePool.getInstance().register(211205, com.mokylin.game.robot.logic.butterfly.handler.ResButterflyOpponentInfoHandler.class, com.mokylin.game.robot.logic.butterfly.message.ResButterflyOpponentInfoMessage.class);
		MessagePool.getInstance().register(100102, com.mokylin.game.robot.logic.login.handler.ResLoginResultHandler.class, com.mokylin.game.robot.logic.login.message.ResLoginResultMessage.class);
		MessagePool.getInstance().register(211204, com.mokylin.game.robot.logic.butterfly.handler.ResButterflyDefendInfoHandler.class, com.mokylin.game.robot.logic.butterfly.message.ResButterflyDefendInfoMessage.class);
		MessagePool.getInstance().register(200203, com.mokylin.game.robot.logic.character.handler.ResCharacterStageResetHandler.class, com.mokylin.game.robot.logic.character.message.ResCharacterStageResetMessage.class);
		MessagePool.getInstance().register(100105, com.mokylin.game.robot.logic.login.handler.ResLoginContinuousLoginDayHandler.class, com.mokylin.game.robot.logic.login.message.ResLoginContinuousLoginDayMessage.class);
		MessagePool.getInstance().register(200202, com.mokylin.game.robot.logic.character.handler.ResCharacterStageUpHandler.class, com.mokylin.game.robot.logic.character.message.ResCharacterStageUpMessage.class);
		MessagePool.getInstance().register(100104, com.mokylin.game.robot.logic.login.handler.ResPlayerDetailHandler.class, com.mokylin.game.robot.logic.login.message.ResPlayerDetailMessage.class);
		MessagePool.getInstance().register(200201, com.mokylin.game.robot.logic.character.handler.ResUnLockCharacterHandler.class, com.mokylin.game.robot.logic.character.message.ResUnLockCharacterMessage.class);
		MessagePool.getInstance().register(211209, com.mokylin.game.robot.logic.butterfly.handler.ResIsButterflyOpenHandler.class, com.mokylin.game.robot.logic.butterfly.message.ResIsButterflyOpenMessage.class);
		MessagePool.getInstance().register(211208, com.mokylin.game.robot.logic.butterfly.handler.ResRefreshButterflyCountHandler.class, com.mokylin.game.robot.logic.butterfly.message.ResRefreshButterflyCountMessage.class);
		MessagePool.getInstance().register(302101, com.mokylin.game.robot.logic.millionluck.handler.ResLuckHandler.class, com.mokylin.game.robot.logic.millionluck.message.ResLuckMessage.class);
		MessagePool.getInstance().register(302102, com.mokylin.game.robot.logic.millionluck.handler.ResReceiveMillionLuckRewardHandler.class, com.mokylin.game.robot.logic.millionluck.message.ResReceiveMillionLuckRewardMessage.class);
		MessagePool.getInstance().register(302103, com.mokylin.game.robot.logic.millionluck.handler.ResLuckWorldRecordHandler.class, com.mokylin.game.robot.logic.millionluck.message.ResLuckWorldRecordMessage.class);
		MessagePool.getInstance().register(206103, com.mokylin.game.robot.logic.arena.handler.ResStartArenaHandler.class, com.mokylin.game.robot.logic.arena.message.ResStartArenaMessage.class);
		MessagePool.getInstance().register(206102, com.mokylin.game.robot.logic.arena.handler.ResArenaOpponentInfoHandler.class, com.mokylin.game.robot.logic.arena.message.ResArenaOpponentInfoMessage.class);
		MessagePool.getInstance().register(206101, com.mokylin.game.robot.logic.arena.handler.ResEnterArenaHandler.class, com.mokylin.game.robot.logic.arena.message.ResEnterArenaMessage.class);
		MessagePool.getInstance().register(206105, com.mokylin.game.robot.logic.arena.handler.ResPlayerArenaInfoHandler.class, com.mokylin.game.robot.logic.arena.message.ResPlayerArenaInfoMessage.class);
		MessagePool.getInstance().register(206104, com.mokylin.game.robot.logic.arena.handler.ResEndArenaHandler.class, com.mokylin.game.robot.logic.arena.message.ResEndArenaMessage.class);
		MessagePool.getInstance().register(206111, com.mokylin.game.robot.logic.arena.handler.ResAddArenaDefendInfoHandler.class, com.mokylin.game.robot.logic.arena.message.ResAddArenaDefendInfoMessage.class);
		MessagePool.getInstance().register(206110, com.mokylin.game.robot.logic.arena.handler.ResArenaDefendInfoHandler.class, com.mokylin.game.robot.logic.arena.message.ResArenaDefendInfoMessage.class);
		MessagePool.getInstance().register(301101, com.mokylin.game.robot.logic.training.handler.ResEnterTrainingHandler.class, com.mokylin.game.robot.logic.training.message.ResEnterTrainingMessage.class);
		MessagePool.getInstance().register(301102, com.mokylin.game.robot.logic.training.handler.ResRefreshTrainingHandler.class, com.mokylin.game.robot.logic.training.message.ResRefreshTrainingMessage.class);
		MessagePool.getInstance().register(205101, com.mokylin.game.robot.logic.reward.handler.ResRewardResultHandler.class, com.mokylin.game.robot.logic.reward.message.ResRewardResultMessage.class);
		MessagePool.getInstance().register(300101, com.mokylin.game.robot.logic.spa.handler.ResEnterSpaHandler.class, com.mokylin.game.robot.logic.spa.message.ResEnterSpaMessage.class);
		MessagePool.getInstance().register(300103, com.mokylin.game.robot.logic.spa.handler.ResGetVitalityFromFriendHandler.class, com.mokylin.game.robot.logic.spa.message.ResGetVitalityFromFriendMessage.class);
		MessagePool.getInstance().register(108101, com.mokylin.game.robot.logic.girl.handler.ResGirlInfoHandler.class, com.mokylin.game.robot.logic.girl.message.ResGirlInfoMessage.class);
		MessagePool.getInstance().register(204103, com.mokylin.game.robot.logic.soultrial.handler.ResStartSoulTrialHandler.class, com.mokylin.game.robot.logic.soultrial.message.ResStartSoulTrialMessage.class);
		MessagePool.getInstance().register(204102, com.mokylin.game.robot.logic.soultrial.handler.ResRestartSoulTrialHandler.class, com.mokylin.game.robot.logic.soultrial.message.ResRestartSoulTrialMessage.class);
		MessagePool.getInstance().register(108103, com.mokylin.game.robot.logic.girl.handler.ResGirlSingleInfoHandler.class, com.mokylin.game.robot.logic.girl.message.ResGirlSingleInfoMessage.class);
		MessagePool.getInstance().register(204101, com.mokylin.game.robot.logic.soultrial.handler.ResSoulTrialInfoHandler.class, com.mokylin.game.robot.logic.soultrial.message.ResSoulTrialInfoMessage.class);
		MessagePool.getInstance().register(108102, com.mokylin.game.robot.logic.girl.handler.ResGirlDateHandler.class, com.mokylin.game.robot.logic.girl.message.ResGirlDateMessage.class);
		MessagePool.getInstance().register(108105, com.mokylin.game.robot.logic.girl.handler.ResGirlEnableAssistSkillHandler.class, com.mokylin.game.robot.logic.girl.message.ResGirlEnableAssistSkillMessage.class);
		MessagePool.getInstance().register(108104, com.mokylin.game.robot.logic.girl.handler.ResGirlGetInfoHandler.class, com.mokylin.game.robot.logic.girl.message.ResGirlGetInfoMessage.class);
		MessagePool.getInstance().register(400202, com.mokylin.game.robot.logic.fighting.handler.ResEndFightingHandler.class, com.mokylin.game.robot.logic.fighting.message.ResEndFightingMessage.class);
		MessagePool.getInstance().register(300104, com.mokylin.game.robot.logic.spa.handler.ResSpaTimesHandler.class, com.mokylin.game.robot.logic.spa.message.ResSpaTimesMessage.class);
		MessagePool.getInstance().register(300105, com.mokylin.game.robot.logic.spa.handler.ResUseVitalityHandler.class, com.mokylin.game.robot.logic.spa.message.ResUseVitalityMessage.class);
		MessagePool.getInstance().register(400201, com.mokylin.game.robot.logic.fighting.handler.ResStartFightingHandler.class, com.mokylin.game.robot.logic.fighting.message.ResStartFightingMessage.class);
		MessagePool.getInstance().register(107101, com.mokylin.game.robot.logic.destiny.handler.ResDestinyInfoHandler.class, com.mokylin.game.robot.logic.destiny.message.ResDestinyInfoMessage.class);
		MessagePool.getInstance().register(203102, com.mokylin.game.robot.logic.buff.handler.ResBuffStopHandler.class, com.mokylin.game.robot.logic.buff.message.ResBuffStopMessage.class);
		MessagePool.getInstance().register(203101, com.mokylin.game.robot.logic.buff.handler.ResBuffStartHandler.class, com.mokylin.game.robot.logic.buff.message.ResBuffStartMessage.class);
		MessagePool.getInstance().register(107102, com.mokylin.game.robot.logic.destiny.handler.ResDestinyFightHandler.class, com.mokylin.game.robot.logic.destiny.message.ResDestinyFightMessage.class);
		MessagePool.getInstance().register(501101, com.mokylin.game.robot.logic.playersync.handler.ResPlayerSyncHandler.class, com.mokylin.game.robot.logic.playersync.message.ResPlayerSyncMessage.class);
		MessagePool.getInstance().register(213101, com.mokylin.game.robot.logic.freshguide.handler.ResFreshGuideInfoHandler.class, com.mokylin.game.robot.logic.freshguide.message.ResFreshGuideInfoMessage.class);
		MessagePool.getInstance().register(202103, com.mokylin.game.robot.logic.record.handler.ResMillionRecordHandler.class, com.mokylin.game.robot.logic.record.message.ResMillionRecordMessage.class);
		MessagePool.getInstance().register(106101, com.mokylin.game.robot.logic.food.handler.ResFoodCookHandler.class, com.mokylin.game.robot.logic.food.message.ResFoodCookMessage.class);
		MessagePool.getInstance().register(202102, com.mokylin.game.robot.logic.record.handler.ResSingleLevelRecordHandler.class, com.mokylin.game.robot.logic.record.message.ResSingleLevelRecordMessage.class);
		MessagePool.getInstance().register(202101, com.mokylin.game.robot.logic.record.handler.ResAllLevelRecordHandler.class, com.mokylin.game.robot.logic.record.message.ResAllLevelRecordMessage.class);
		MessagePool.getInstance().register(106103, com.mokylin.game.robot.logic.food.handler.ResFoodTimesHandler.class, com.mokylin.game.robot.logic.food.message.ResFoodTimesMessage.class);
		MessagePool.getInstance().register(106102, com.mokylin.game.robot.logic.food.handler.ResFoodClearTimeHandler.class, com.mokylin.game.robot.logic.food.message.ResFoodClearTimeMessage.class);
		MessagePool.getInstance().register(500103, com.mokylin.game.robot.logic.mail.handler.ResDeleteMailHandler.class, com.mokylin.game.robot.logic.mail.message.ResDeleteMailMessage.class);
		MessagePool.getInstance().register(500102, com.mokylin.game.robot.logic.mail.handler.ResGetMailAttachHandler.class, com.mokylin.game.robot.logic.mail.message.ResGetMailAttachMessage.class);
		MessagePool.getInstance().register(500101, com.mokylin.game.robot.logic.mail.handler.ResReadMailHandler.class, com.mokylin.game.robot.logic.mail.message.ResReadMailMessage.class);
		MessagePool.getInstance().register(105101, com.mokylin.game.robot.logic.player.handler.ResPlayerAttrChangeHandler.class, com.mokylin.game.robot.logic.player.message.ResPlayerAttrChangeMessage.class);
		MessagePool.getInstance().register(500105, com.mokylin.game.robot.logic.mail.handler.ResAllMailInfoHandler.class, com.mokylin.game.robot.logic.mail.message.ResAllMailInfoMessage.class);
		MessagePool.getInstance().register(105103, com.mokylin.game.robot.logic.player.handler.ResPlayerAttributeHandler.class, com.mokylin.game.robot.logic.player.message.ResPlayerAttributeMessage.class);
		MessagePool.getInstance().register(201101, com.mokylin.game.robot.logic.errormessage.handler.ResErrorHandler.class, com.mokylin.game.robot.logic.errormessage.message.ResErrorMessage.class);
		MessagePool.getInstance().register(500104, com.mokylin.game.robot.logic.mail.handler.ResReceiveMailHandler.class, com.mokylin.game.robot.logic.mail.message.ResReceiveMailMessage.class);
		MessagePool.getInstance().register(105102, com.mokylin.game.robot.logic.player.handler.ResPlayerAttributesHandler.class, com.mokylin.game.robot.logic.player.message.ResPlayerAttributesMessage.class);
		MessagePool.getInstance().register(105105, com.mokylin.game.robot.logic.player.handler.ResRecoverHealthHandler.class, com.mokylin.game.robot.logic.player.message.ResRecoverHealthMessage.class);
		MessagePool.getInstance().register(105107, com.mokylin.game.robot.logic.player.handler.ResPlayerActivityDiscountHandler.class, com.mokylin.game.robot.logic.player.message.ResPlayerActivityDiscountMessage.class);
		MessagePool.getInstance().register(105106, com.mokylin.game.robot.logic.player.handler.ResPlayerGmHandler.class, com.mokylin.game.robot.logic.player.message.ResPlayerGmMessage.class);
		MessagePool.getInstance().register(105109, com.mokylin.game.robot.logic.player.handler.ResPlayerSkillPointRecoverHandler.class, com.mokylin.game.robot.logic.player.message.ResPlayerSkillPointRecoverMessage.class);
		MessagePool.getInstance().register(105108, com.mokylin.game.robot.logic.player.handler.ResPlayerTestHandler.class, com.mokylin.game.robot.logic.player.message.ResPlayerTestMessage.class);
		MessagePool.getInstance().register(104101, com.mokylin.game.robot.logic.shop.handler.ResShopInfoHandler.class, com.mokylin.game.robot.logic.shop.message.ResShopInfoMessage.class);
		MessagePool.getInstance().register(104103, com.mokylin.game.robot.logic.shop.handler.ResShopPuyuanTimesHandler.class, com.mokylin.game.robot.logic.shop.message.ResShopPuyuanTimesMessage.class);
		MessagePool.getInstance().register(104102, com.mokylin.game.robot.logic.shop.handler.ResShopBuyHandler.class, com.mokylin.game.robot.logic.shop.message.ResShopBuyMessage.class);
		MessagePool.getInstance().register(104104, com.mokylin.game.robot.logic.shop.handler.ResShopJingjiTimesHandler.class, com.mokylin.game.robot.logic.shop.message.ResShopJingjiTimesMessage.class);
		MessagePool.getInstance().register(210102, com.mokylin.game.robot.logic.achievement.handler.ResAchievementRewardHandler.class, com.mokylin.game.robot.logic.achievement.message.ResAchievementRewardMessage.class);
		MessagePool.getInstance().register(210101, com.mokylin.game.robot.logic.achievement.handler.ResAchievementInfoHandler.class, com.mokylin.game.robot.logic.achievement.message.ResAchievementInfoMessage.class);
		MessagePool.getInstance().register(103101, com.mokylin.game.robot.logic.equip.handler.ResEquipLevelUpHandler.class, com.mokylin.game.robot.logic.equip.message.ResEquipLevelUpMessage.class);
		MessagePool.getInstance().register(305101, com.mokylin.game.robot.logic.signin.handler.ResSigninHandler.class, com.mokylin.game.robot.logic.signin.message.ResSigninMessage.class);
		MessagePool.getInstance().register(305102, com.mokylin.game.robot.logic.signin.handler.ResResetSigninHandler.class, com.mokylin.game.robot.logic.signin.message.ResResetSigninMessage.class);
		MessagePool.getInstance().register(209102, com.mokylin.game.robot.logic.ranking.handler.ResArenaRankingUpdateHandler.class, com.mokylin.game.robot.logic.ranking.message.ResArenaRankingUpdateMessage.class);
		MessagePool.getInstance().register(209101, com.mokylin.game.robot.logic.ranking.handler.ResArenaRankingInfoHandler.class, com.mokylin.game.robot.logic.ranking.message.ResArenaRankingInfoMessage.class);
		MessagePool.getInstance().register(102101, com.mokylin.game.robot.logic.level.handler.ResClearanceInfoHandler.class, com.mokylin.game.robot.logic.level.message.ResClearanceInfoMessage.class);
		MessagePool.getInstance().register(102103, com.mokylin.game.robot.logic.level.handler.ResEnterLevelHandler.class, com.mokylin.game.robot.logic.level.message.ResEnterLevelMessage.class);
		MessagePool.getInstance().register(102102, com.mokylin.game.robot.logic.level.handler.ResMopInfoHandler.class, com.mokylin.game.robot.logic.level.message.ResMopInfoMessage.class);
		MessagePool.getInstance().register(304101, com.mokylin.game.robot.logic.soulability.handler.ResSoulAbilityUpgradeHandler.class, com.mokylin.game.robot.logic.soulability.message.ResSoulAbilityUpgradeMessage.class);
		MessagePool.getInstance().register(304102, com.mokylin.game.robot.logic.soulability.handler.ResSoulAbilityActivateHandler.class, com.mokylin.game.robot.logic.soulability.message.ResSoulAbilityActivateMessage.class);
		MessagePool.getInstance().register(304103, com.mokylin.game.robot.logic.soulability.handler.ResSoulAbilityInfoChangeHandler.class, com.mokylin.game.robot.logic.soulability.message.ResSoulAbilityInfoChangeMessage.class);
		MessagePool.getInstance().register(208102, com.mokylin.game.robot.logic.skill.handler.ResSkillAssistSkillHandler.class, com.mokylin.game.robot.logic.skill.message.ResSkillAssistSkillMessage.class);
		MessagePool.getInstance().register(208101, com.mokylin.game.robot.logic.skill.handler.ResCharacterSkillsHandler.class, com.mokylin.game.robot.logic.skill.message.ResCharacterSkillsMessage.class);
		MessagePool.getInstance().register(212201, com.mokylin.game.robot.logic.lottery.handler.ResSyncLotteryInfoHandler.class, com.mokylin.game.robot.logic.lottery.message.ResSyncLotteryInfoMessage.class);
		MessagePool.getInstance().register(304104, com.mokylin.game.robot.logic.soulability.handler.ResBuySkillPointHandler.class, com.mokylin.game.robot.logic.soulability.message.ResBuySkillPointMessage.class);
		MessagePool.getInstance().register(101101, com.mokylin.game.robot.logic.item.handler.ResItemInfoHandler.class, com.mokylin.game.robot.logic.item.message.ResItemInfoMessage.class);
		MessagePool.getInstance().register(101102, com.mokylin.game.robot.logic.item.handler.ResSingleItemInfoHandler.class, com.mokylin.game.robot.logic.item.message.ResSingleItemInfoMessage.class);
		MessagePool.getInstance().register(303101, com.mokylin.game.robot.logic.discovery.handler.ResBeginDiscoveryHandler.class, com.mokylin.game.robot.logic.discovery.message.ResBeginDiscoveryMessage.class);
		MessagePool.getInstance().register(303102, com.mokylin.game.robot.logic.discovery.handler.ResReceiveDiscoveryRewardHandler.class, com.mokylin.game.robot.logic.discovery.message.ResReceiveDiscoveryRewardMessage.class);
		MessagePool.getInstance().register(303103, com.mokylin.game.robot.logic.discovery.handler.ResDiscoveryCharacterRefreshHandler.class, com.mokylin.game.robot.logic.discovery.message.ResDiscoveryCharacterRefreshMessage.class);
		MessagePool.getInstance().register(207101, com.mokylin.game.robot.logic.exchange.handler.ResExchangeInfoHandler.class, com.mokylin.game.robot.logic.exchange.message.ResExchangeInfoMessage.class);
		return true;
	}
}
