// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map.proto

package com.mokylin.game.server.proto;

public final class MapProto {
  private MapProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MapDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MapData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 model = 1;</code>
     */
    boolean hasModel();
    /**
     * <code>required int32 model = 1;</code>
     */
    int getModel();

    /**
     * <code>required .CoordinateData coordinate = 2;</code>
     */
    boolean hasCoordinate();
    /**
     * <code>required .CoordinateData coordinate = 2;</code>
     */
    com.mokylin.game.server.proto.CoordinateProto.CoordinateData getCoordinate();
    /**
     * <code>required .CoordinateData coordinate = 2;</code>
     */
    com.mokylin.game.server.proto.CoordinateProto.CoordinateDataOrBuilder getCoordinateOrBuilder();
  }
  /**
   * Protobuf type {@code MapData}
   */
  public static final class MapData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MapData)
      MapDataOrBuilder {
    // Use MapData.newBuilder() to construct.
    private MapData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MapData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MapData defaultInstance;
    public static MapData getDefaultInstance() {
      return defaultInstance;
    }

    public MapData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MapData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              model_ = input.readInt32();
              break;
            }
            case 18: {
              com.mokylin.game.server.proto.CoordinateProto.CoordinateData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = coordinate_.toBuilder();
              }
              coordinate_ = input.readMessage(com.mokylin.game.server.proto.CoordinateProto.CoordinateData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(coordinate_);
                coordinate_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mokylin.game.server.proto.MapProto.internal_static_MapData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mokylin.game.server.proto.MapProto.internal_static_MapData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mokylin.game.server.proto.MapProto.MapData.class, com.mokylin.game.server.proto.MapProto.MapData.Builder.class);
    }

    public static com.google.protobuf.Parser<MapData> PARSER =
        new com.google.protobuf.AbstractParser<MapData>() {
      public MapData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MapData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MapData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MODEL_FIELD_NUMBER = 1;
    private int model_;
    /**
     * <code>required int32 model = 1;</code>
     */
    public boolean hasModel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 model = 1;</code>
     */
    public int getModel() {
      return model_;
    }

    public static final int COORDINATE_FIELD_NUMBER = 2;
    private com.mokylin.game.server.proto.CoordinateProto.CoordinateData coordinate_;
    /**
     * <code>required .CoordinateData coordinate = 2;</code>
     */
    public boolean hasCoordinate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .CoordinateData coordinate = 2;</code>
     */
    public com.mokylin.game.server.proto.CoordinateProto.CoordinateData getCoordinate() {
      return coordinate_;
    }
    /**
     * <code>required .CoordinateData coordinate = 2;</code>
     */
    public com.mokylin.game.server.proto.CoordinateProto.CoordinateDataOrBuilder getCoordinateOrBuilder() {
      return coordinate_;
    }

    private void initFields() {
      model_ = 0;
      coordinate_ = com.mokylin.game.server.proto.CoordinateProto.CoordinateData.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasModel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCoordinate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCoordinate().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, model_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, coordinate_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, model_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, coordinate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mokylin.game.server.proto.MapProto.MapData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mokylin.game.server.proto.MapProto.MapData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mokylin.game.server.proto.MapProto.MapData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mokylin.game.server.proto.MapProto.MapData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mokylin.game.server.proto.MapProto.MapData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mokylin.game.server.proto.MapProto.MapData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mokylin.game.server.proto.MapProto.MapData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mokylin.game.server.proto.MapProto.MapData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mokylin.game.server.proto.MapProto.MapData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mokylin.game.server.proto.MapProto.MapData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mokylin.game.server.proto.MapProto.MapData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MapData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MapData)
        com.mokylin.game.server.proto.MapProto.MapDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mokylin.game.server.proto.MapProto.internal_static_MapData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mokylin.game.server.proto.MapProto.internal_static_MapData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mokylin.game.server.proto.MapProto.MapData.class, com.mokylin.game.server.proto.MapProto.MapData.Builder.class);
      }

      // Construct using com.mokylin.game.server.proto.MapProto.MapData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCoordinateFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        model_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (coordinateBuilder_ == null) {
          coordinate_ = com.mokylin.game.server.proto.CoordinateProto.CoordinateData.getDefaultInstance();
        } else {
          coordinateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mokylin.game.server.proto.MapProto.internal_static_MapData_descriptor;
      }

      public com.mokylin.game.server.proto.MapProto.MapData getDefaultInstanceForType() {
        return com.mokylin.game.server.proto.MapProto.MapData.getDefaultInstance();
      }

      public com.mokylin.game.server.proto.MapProto.MapData build() {
        com.mokylin.game.server.proto.MapProto.MapData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mokylin.game.server.proto.MapProto.MapData buildPartial() {
        com.mokylin.game.server.proto.MapProto.MapData result = new com.mokylin.game.server.proto.MapProto.MapData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.model_ = model_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (coordinateBuilder_ == null) {
          result.coordinate_ = coordinate_;
        } else {
          result.coordinate_ = coordinateBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mokylin.game.server.proto.MapProto.MapData) {
          return mergeFrom((com.mokylin.game.server.proto.MapProto.MapData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mokylin.game.server.proto.MapProto.MapData other) {
        if (other == com.mokylin.game.server.proto.MapProto.MapData.getDefaultInstance()) return this;
        if (other.hasModel()) {
          setModel(other.getModel());
        }
        if (other.hasCoordinate()) {
          mergeCoordinate(other.getCoordinate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasModel()) {
          
          return false;
        }
        if (!hasCoordinate()) {
          
          return false;
        }
        if (!getCoordinate().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mokylin.game.server.proto.MapProto.MapData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mokylin.game.server.proto.MapProto.MapData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int model_ ;
      /**
       * <code>required int32 model = 1;</code>
       */
      public boolean hasModel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 model = 1;</code>
       */
      public int getModel() {
        return model_;
      }
      /**
       * <code>required int32 model = 1;</code>
       */
      public Builder setModel(int value) {
        bitField0_ |= 0x00000001;
        model_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 model = 1;</code>
       */
      public Builder clearModel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        model_ = 0;
        onChanged();
        return this;
      }

      private com.mokylin.game.server.proto.CoordinateProto.CoordinateData coordinate_ = com.mokylin.game.server.proto.CoordinateProto.CoordinateData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.mokylin.game.server.proto.CoordinateProto.CoordinateData, com.mokylin.game.server.proto.CoordinateProto.CoordinateData.Builder, com.mokylin.game.server.proto.CoordinateProto.CoordinateDataOrBuilder> coordinateBuilder_;
      /**
       * <code>required .CoordinateData coordinate = 2;</code>
       */
      public boolean hasCoordinate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .CoordinateData coordinate = 2;</code>
       */
      public com.mokylin.game.server.proto.CoordinateProto.CoordinateData getCoordinate() {
        if (coordinateBuilder_ == null) {
          return coordinate_;
        } else {
          return coordinateBuilder_.getMessage();
        }
      }
      /**
       * <code>required .CoordinateData coordinate = 2;</code>
       */
      public Builder setCoordinate(com.mokylin.game.server.proto.CoordinateProto.CoordinateData value) {
        if (coordinateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          coordinate_ = value;
          onChanged();
        } else {
          coordinateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .CoordinateData coordinate = 2;</code>
       */
      public Builder setCoordinate(
          com.mokylin.game.server.proto.CoordinateProto.CoordinateData.Builder builderForValue) {
        if (coordinateBuilder_ == null) {
          coordinate_ = builderForValue.build();
          onChanged();
        } else {
          coordinateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .CoordinateData coordinate = 2;</code>
       */
      public Builder mergeCoordinate(com.mokylin.game.server.proto.CoordinateProto.CoordinateData value) {
        if (coordinateBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              coordinate_ != com.mokylin.game.server.proto.CoordinateProto.CoordinateData.getDefaultInstance()) {
            coordinate_ =
              com.mokylin.game.server.proto.CoordinateProto.CoordinateData.newBuilder(coordinate_).mergeFrom(value).buildPartial();
          } else {
            coordinate_ = value;
          }
          onChanged();
        } else {
          coordinateBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .CoordinateData coordinate = 2;</code>
       */
      public Builder clearCoordinate() {
        if (coordinateBuilder_ == null) {
          coordinate_ = com.mokylin.game.server.proto.CoordinateProto.CoordinateData.getDefaultInstance();
          onChanged();
        } else {
          coordinateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .CoordinateData coordinate = 2;</code>
       */
      public com.mokylin.game.server.proto.CoordinateProto.CoordinateData.Builder getCoordinateBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCoordinateFieldBuilder().getBuilder();
      }
      /**
       * <code>required .CoordinateData coordinate = 2;</code>
       */
      public com.mokylin.game.server.proto.CoordinateProto.CoordinateDataOrBuilder getCoordinateOrBuilder() {
        if (coordinateBuilder_ != null) {
          return coordinateBuilder_.getMessageOrBuilder();
        } else {
          return coordinate_;
        }
      }
      /**
       * <code>required .CoordinateData coordinate = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.mokylin.game.server.proto.CoordinateProto.CoordinateData, com.mokylin.game.server.proto.CoordinateProto.CoordinateData.Builder, com.mokylin.game.server.proto.CoordinateProto.CoordinateDataOrBuilder> 
          getCoordinateFieldBuilder() {
        if (coordinateBuilder_ == null) {
          coordinateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.mokylin.game.server.proto.CoordinateProto.CoordinateData, com.mokylin.game.server.proto.CoordinateProto.CoordinateData.Builder, com.mokylin.game.server.proto.CoordinateProto.CoordinateDataOrBuilder>(
                  getCoordinate(),
                  getParentForChildren(),
                  isClean());
          coordinate_ = null;
        }
        return coordinateBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:MapData)
    }

    static {
      defaultInstance = new MapData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MapData)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MapData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MapData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmap.proto\032\020coordinate.proto\"=\n\007MapData" +
      "\022\r\n\005model\030\001 \002(\005\022#\n\ncoordinate\030\002 \002(\0132\017.Co" +
      "ordinateDataB)\n\035com.mokylin.game.server." +
      "protoB\010MapProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.mokylin.game.server.proto.CoordinateProto.getDescriptor(),
        }, assigner);
    internal_static_MapData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MapData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MapData_descriptor,
        new java.lang.String[] { "Model", "Coordinate", });
    com.mokylin.game.server.proto.CoordinateProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
